name: analog_clock
description: Analog clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: WeatherIcons
      fonts:
        - asset: assets/fonts/weathericons-regular-webfont.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto_Mono/RobotoMono-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Mono/RobotoMono-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto_Mono/RobotoMono-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_Mono/RobotoMono-BoldItalic.ttf
          style: italic
          weight: 700
    - family: FiraSans
      fonts:
        - asset: assets/fonts/Fira_Sans/FiraSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/Fira_Sans/FiraSans-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Fira_Sans/FiraSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Fira_Sans/FiraSans-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Fira_Sans/FiraSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Fira_Sans/FiraSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Fira_Sans/FiraSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fira_Sans/FiraSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Fira_Sans/FiraSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fira_Sans/FiraSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Fira_Sans/FiraSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fira_Sans/FiraSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Fira_Sans/FiraSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Fira_Sans/FiraSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Fira_Sans/FiraSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Fira_Sans/FiraSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Fira_Sans/FiraSans-Black.ttf
          weight: 900
        - asset: assets/fonts/Fira_Sans/FiraSans-BlackItalic.ttf
          style: italic
          weight: 900
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Black.ttf
          weight: 900
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-BlackItalic.ttf
          style: italic
          weight: 900