name: analog_clock
description: Analog clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: WeatherIcons
      fonts:
        - asset: assets/fonts/weathericons-regular-webfont.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/RobotoMono-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoMono-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMono-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono-BoldItalic.ttf
          style: italic
          weight: 700